<?php
/**
 * Email Inbox Viewer - See all generated emails
 */

require_once '../config/config.php';

$emailDir = __DIR__ . '/../tmp/emails';

echo "<h1>📧 Generated Emails Inbox</h1>";
echo "<hr>";

if (!is_dir($emailDir)) {
    echo "<p>No emails have been generated yet. Approve or cancel a reservation to generate an email.</p>";
    echo "<p><a href='reservations.php'>← Go to Reservations</a></p>";
    exit;
}

$files = array_diff(scandir($emailDir, SCANDIR_SORT_DESCENDING), ['.', '..']);

if (empty($files)) {
    echo "<p>No emails have been generated yet.</p>";
    echo "<p><a href='reservations.php'>← Go to Reservations</a></p>";
    exit;
}

?>

<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #f5f5f5;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        .email-list {
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .email-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px 20px;
            border-bottom: 1px solid #eee;
            cursor: pointer;
            transition: background 0.2s;
        }
        .email-item:hover {
            background: #f9f9f9;
        }
        .email-item:last-child {
            border-bottom: none;
        }
        .email-info {
            flex: 1;
        }
        .email-type {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: bold;
            margin-right: 10px;
        }
        .approval {
            background: #d4edda;
            color: #155724;
        }
        .cancellation {
            background: #f8d7da;
            color: #721c24;
        }
        .email-time {
            font-size: 12px;
            color: #999;
            margin-top: 5px;
        }
        .email-actions {
            text-align: right;
        }
        .btn {
            padding: 8px 15px;
            margin-left: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 12px;
        }
        .btn-view {
            background: #1e3a8a;
            color: white;
        }
        .btn-delete {
            background: #dc3545;
            color: white;
        }
        .email-preview {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(0,0,0,0.7);
            z-index: 1000;
            padding: 20px;
        }
        .email-preview.show {
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .preview-content {
            background: white;
            border-radius: 8px;
            max-width: 90%;
            max-height: 90vh;
            overflow: auto;
            padding: 20px;
            position: relative;
        }
        .close-btn {
            position: absolute;
            top: 10px;
            right: 10px;
            background: #dc3545;
            color: white;
            border: none;
            padding: 8px 15px;
            border-radius: 4px;
            cursor: pointer;
        }
        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 20px;
        }
        .stat-card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
        }
        .stat-number {
            font-size: 32px;
            font-weight: bold;
            color: #1e3a8a;
        }
        .stat-label {
            color: #999;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📧 Email Inbox</h1>
        <p>All emails generated by the system. These are saved for verification purposes.</p>
        
        <div class="stats">
            <div class="stat-card">
                <div class="stat-number"><?php echo count($files); ?></div>
                <div class="stat-label">Total Emails</div>
            </div>
            <div class="stat-card">
                <div class="stat-number"><?php echo count(array_filter($files, function($f) { return strpos($f, 'approval') !== false; })); ?></div>
                <div class="stat-label">Approvals</div>
            </div>
            <div class="stat-card">
                <div class="stat-number"><?php echo count(array_filter($files, function($f) { return strpos($f, 'cancellation') !== false; })); ?></div>
                <div class="stat-label">Cancellations</div>
            </div>
        </div>
        
        <div class="email-list">
            <?php foreach ($files as $file): 
                $filePath = $emailDir . '/' . $file;
                $isApproval = strpos($file, 'approval') !== false;
                $type = $isApproval ? 'approval' : 'cancellation';
                $typeLabel = $isApproval ? 'APPROVAL' : 'CANCELLATION';
                $fileTime = filemtime($filePath);
                $fileDate = date('M d, Y H:i:s', $fileTime);
                $reservationId = preg_match('/_(\\d+)_/', $file, $m) ? $m[1] : '?';
            ?>
                <div class="email-item" onclick="viewEmail('<?php echo htmlspecialchars($file); ?>')">
                    <div class="email-info">
                        <div>
                            <span class="email-type <?php echo $type; ?>"><?php echo $typeLabel; ?></span>
                            <strong>Reservation #<?php echo $reservationId; ?></strong>
                        </div>
                        <div class="email-time"><?php echo $fileDate; ?></div>
                    </div>
                    <div class="email-actions">
                        <button class="btn btn-view" onclick="viewEmail('<?php echo htmlspecialchars($file); ?>'); return false;">View</button>
                        <button class="btn btn-delete" onclick="deleteEmail('<?php echo htmlspecialchars($file); ?>'); return false;">Delete</button>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        
        <p style="margin-top: 20px;">
            <a href="reservations.php" style="padding: 10px 20px; background: #1e3a8a; color: white; border-radius: 4px; text-decoration: none;">← Back to Reservations</a>
        </p>
    </div>

    <div id="emailPreview" class="email-preview">
        <div class="preview-content">
            <button class="close-btn" onclick="closePreview()">Close</button>
            <div id="previewBody"></div>
        </div>
    </div>

    <script>
        function viewEmail(filename) {
            fetch('email_view.php?file=' + encodeURIComponent(filename))
                .then(r => r.text())
                .then(content => {
                    document.getElementById('previewBody').innerHTML = content;
                    document.getElementById('emailPreview').classList.add('show');
                });
        }
        
        function closePreview() {
            document.getElementById('emailPreview').classList.remove('show');
        }
        
        function deleteEmail(filename) {
            if (confirm('Delete this email?')) {
                fetch('email_delete.php?file=' + encodeURIComponent(filename))
                    .then(r => r.json())
                    .then(data => {
                        if (data.success) {
                            location.reload();
                        } else {
                            alert('Error deleting email');
                        }
                    });
            }
        }
    </script>
</body>
</html>
<?php
